Still running errors in the code
bot = updater.bot